### ISSUE TITLE
Design and creating the motor drivers

### ISSUE THREAD

**Issue by N0hen** [Boti21/SDU-SPRO3#55]
# Description
Design and create the motor drivers so they are compatible with the chosen motors. As stated in a email from Jonas it is possible to have pcb created if correct Gerber files are send to him. 

Note: Due to waiting time for pcb manufacturing this issue will run over multiple sprints. 

Estimated time: 8h

# Task goals
* Create a circuit diagram of the drivers
* Set the design in production
* Solider and wire it up if necessary  
* Test that all functionality are working

**Comment by timen2011** [comment]
<img width="504" alt="Screenshot 2023-11-29 at 14 13 52" src="https://github.com/Boti21/SDU-SPRO3/assets/145134519/d4207cbc-dbd7-4b39-81d7-007bb27ace58">

**Comment by timen2011** [comment]
Done.
